<!DOCTYPE html>
<head>
    <h1> JavaScript async</h1>
</head>
<body>
    <script>
        let result=function(score){
            return new Promise(function(resolve,reject){
                console.log("Calculate results...")
                if(score>50)
                resolve("congratulation! you have passed")
                else 
                reject("you have failed")
            }) 
        }
        let grade = function (response){
            return new Promise(function (resolve,reject){
                console.log("calculating your grade..")
                resolve("your grade is A. " + response)
            })
        }
        //  result(51).then(response=>{
        //     console.log("result recived")
        //     return grade(response)
        // }).then(finalgrade =>{
        //     console.log(finalgrade)
        // }).catch(err =>{
        //     console.log(err)
        // })
        async function calculateResult(){
            try{  //try is used for checking the errors
            const response= await result(60)
            console.log("result recived")
            const finalgrade=await grade(response)
            console.log(finalgrade)
            }
            catch(err){
                console.log(err)
            }
        }
        calculateResult()
    </script>
</body>
</html>
